FROM python:3.6-alpine

RUN apk add --update tini
RUN apk add --update build-base
RUN apk add --update libffi-dev
RUN pip install pipenv

RUN mkdir /bot
COPY Pipfile /bot
COPY Pipfile.lock /bot
WORKDIR /bot

ENV PIPENV_VENV_IN_PROJECT=1
ENV PIPENV_IGNORE_VIRTUALENVS=1
ENV PIPENV_NOSPIN=1
ENV PIPENV_HIDE_EMOJIS=1

RUN pipenv install

# usage: FROM pythondiscord/bot-base:latest
