# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pipenv
        pipenv install --dev
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # Talked with Professor Santore about having 9 functions being to complex, told me to ignore C901 and W504 errors
        flake8 . --count  --max-complexity=10 --max-line-length=127 --statistics --ignore=C901,W504
    - name: Test with Unit Tests
      run: |
        pipenv run test
      env:
          BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
